In [1]:
import pandas as pd
df = pd.read_excel(r"C:\Users\hppat\OneDrive\Desktop\Untangle_zeroClutter\model\bank.xlsx")

In [27]:
df.head()

,Account No,DATE,TRANSACTION DETAILS,CHQ.NO.,VALUE DATE,WITHDRAWAL AMT,DEPOSIT AMT,BALANCE AMT,.
0,409000611074',2017-06-29,TRF FROM Indiaforensic SERVICES,NaN,2017-06-29,NaN,1000000.0,1000000.0,.
1,409000611074',2017-07-05,TRF FROM Indiaforensic SERVICES,NaN,2017-07-05,NaN,1000000.0,2000000.0,.
2,409000611074',2017-07-18,FDRL/INTERNAL FUND TRANSFE,NaN,2017-07-18,NaN,500000.0,2500000.0,.
3,409000611074',2017-08-01,TRF FRM Indiaforensic SERVICES,NaN,2017-08-01,NaN,3000000.0,5500000.0,.
4,409000611074',2017-08-16,FDRL/INTERNAL FUND TRANSFE,NaN,2017-08-16,NaN,500000.0,6000000.0,.

In [28]:
df.columns

Index(['Account No', 'DATE', 'TRANSACTION DETAILS', 'CHQ.NO.', 'VALUE DATE',
       'WITHDRAWAL AMT', 'DEPOSIT AMT', 'BALANCE AMT', '.'],
      dtype='str')

In [29]:
df.shape

(116201, 9)

In [30]:
df.groupby(['Account No']).agg('count')

,DATE,TRANSACTION DETAILS,CHQ.NO.,VALUE DATE,WITHDRAWAL AMT,DEPOSIT AMT,BALANCE AMT,.
Account No,,,,,,,,
1196428',48779,48779,323,48779,16687,32092,48779,48779
1196711',10536,10521,561,10536,5025,5511,10536,10536
409000362497',29840,27356,0,29840,15477,14363,29840,29840
409000405747',51,51,0,51,28,23,51,51
409000425051',802,802,9,802,28,774,802,802
409000438611',4588,4588,4,4588,1333,3255,4588,4588
409000438620',13454,13454,8,13454,8391,5063,13454,13454
409000493201',1044,1044,0,1044,575,469,1044,1044
409000493210',6014,6014,0,6014,5227,787,6014,6014
409000611074',1093,1093,0,1093,778,315,1093,1093

In [31]:
df1 = df.drop(['.'], axis="columns")
df1.head()

,Account No,DATE,TRANSACTION DETAILS,CHQ.NO.,VALUE DATE,WITHDRAWAL AMT,DEPOSIT AMT,BALANCE AMT
0,409000611074',2017-06-29,TRF FROM Indiaforensic SERVICES,NaN,2017-06-29,NaN,1000000.0,1000000.0
1,409000611074',2017-07-05,TRF FROM Indiaforensic SERVICES,NaN,2017-07-05,NaN,1000000.0,2000000.0
2,409000611074',2017-07-18,FDRL/INTERNAL FUND TRANSFE,NaN,2017-07-18,NaN,500000.0,2500000.0
3,409000611074',2017-08-01,TRF FRM Indiaforensic SERVICES,NaN,2017-08-01,NaN,3000000.0,5500000.0
4,409000611074',2017-08-16,FDRL/INTERNAL FUND TRANSFE,NaN,2017-08-16,NaN,500000.0,6000000.0

In [32]:
df1['DATE'] = pd.to_datetime(df1['DATE'])

In [33]:
df1.isnull().sum()

Account No                  0
DATE                        0
TRANSACTION DETAILS      2499
CHQ.NO.                115296
VALUE DATE                  0
WITHDRAWAL AMT          62652
DEPOSIT AMT             53549
BALANCE AMT                 0
dtype: int64

In [34]:
df1.dropna(subset=['TRANSACTION DETAILS'], inplace=True)

In [35]:
df1.isnull().sum()

Account No                  0
DATE                        0
TRANSACTION DETAILS         0
CHQ.NO.                112797
VALUE DATE                  0
WITHDRAWAL AMT          60153
DEPOSIT AMT             53549
BALANCE AMT                 0
dtype: int64

In [36]:
df1["WITHDRAWAL AMT"].fillna(0, inplace=True)

C:\Users\hppat\AppData\Local\Temp\ipykernel_27764\474798480.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df1["WITHDRAWAL AMT"].fillna(0, inplace=True)

0              0.00
1              0.00
2              0.00
3              0.00
4              0.00
            ...
116196    117934.30
116197         0.00
116198         0.00
116199    109868.65
116200      5000.00
Name: WITHDRAWAL AMT, Length: 113702, dtype: float64

In [37]:
df1["DEPOSIT AMT"].fillna(0, inplace=True)

C:\Users\hppat\AppData\Local\Temp\ipykernel_27764\999116991.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df1["DEPOSIT AMT"].fillna(0, inplace=True)

0         1000000.0
1         1000000.0
2          500000.0
3         3000000.0
4          500000.0
            ...
116196          0.0
116197     300000.0
116198     300000.0
116199          0.0
116200          0.0
Name: DEPOSIT AMT, Length: 113702, dtype: float64

In [39]:
df1["CHQ.NO."].fillna("unknown", inplace=True)

C:\Users\hppat\AppData\Local\Temp\ipykernel_27764\2964009970.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df1["CHQ.NO."].fillna("unknown", inplace=True)

TypeError: Invalid value 'unknown' for dtype 'float64'

In [40]:
df1 = df1[df1['BALANCE AMT'] > -1000000]

In [41]:
df1.describe()

,DATE,CHQ.NO.,VALUE DATE,WITHDRAWAL AMT,DEPOSIT AMT,BALANCE AMT
count,2925,9.000000,2925,1.373000e+03,1.552000e+03,2.925000e+03
mean,2017-11-23 05:30:20.307692,5.000000,2017-11-23 05:30:20.307692,1.787891e+05,1.681293e+05,1.204283e+06
min,2016-02-23 00:00:00,1.000000,2016-02-23 00:00:00,1.250000e+00,9.000000e-01,1.383550e+05
25%,2016-12-08 00:00:00,3.000000,2016-12-08 00:00:00,2.000000e+04,5.000000e+03,8.211816e+05
50%,2017-12-27 00:00:00,5.000000,2017-12-27 00:00:00,1.119625e+05,2.100000e+04,1.087909e+06
75%,2018-08-24 00:00:00,7.000000,2018-08-24 00:00:00,2.343199e+05,3.000000e+05,1.383087e+06
max,2019-03-05 00:00:00,9.000000,2019-03-05 00:00:00,2.500000e+06,1.500000e+07,8.500000e+06
std,NaN,2.738613,NaN,2.306569e+05,4.322445e+05,7.820032e+05

In [42]:
import matplotlib.pyplot as plt

df1[['WITHDRAWAL AMT','DEPOSIT AMT']].boxplot()
plt.show()

ModuleNotFoundError: No module named 'matplotlib'

In [43]:
Q1 = df1['WITHDRAWAL AMT'].quantile(0.25)
Q3 = df1['WITHDRAWAL AMT'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df1[(df1['WITHDRAWAL AMT'] < lower) | (df1['WITHDRAWAL AMT'] > upper)]

In [44]:
df1.shape

(2925, 8)

In [45]:
df1['TRANSACTION DETAILS'].unique()

array(['TRF FROM  Indiaforensic SERVICES', 'FDRL/INTERNAL FUND TRANSFE',
       'TRF FRM  Indiaforensic SERVICES', ...,
       'TRF TO  Indiaforensic ONLINE SER', 720717634445,
       'IMPS 809712134438 FROM OX'], shape=(2039,), dtype=object)

In [46]:
df1['TRANSACTION DETAILS'].nunique()

2039

In [47]:
import re

def clean_text(text):
    text = str(text).lower()
    
    text = re.sub(r'\d+', '', text)
    
    text = re.sub(r'[/,:*.-]', ' ', text)
    
    text = re.sub(r'\s+', ' ', text).strip()
    
    return text

df1["clean_desc"] = df1["TRANSACTION DETAILS"].apply(clean_text)

In [48]:
def detect_type(text):
    text = str(text).lower()
    
    if "trf from" in text:
        return "income"
    elif "trf to" in text or "sweep" in text:
        return "transfer"
    elif "neft" in text or "imps" in text or "upi" in text:
        return "bank_transfer"
    else:
        return "expense"

df1["type"] = df1["TRANSACTION DETAILS"].apply(detect_type)

In [49]:
df1["clean_desc"] = df1["clean_desc"].fillna("unknown").astype(str).apply(remove_stopwords)

In [50]:
def extract_merchant(text):
    words = text.split()
    
    if len(words) == 0:
        return "unknown"
    
    return " ".join(words[:2])  # first 2 words

df1["merchant"] = df1["clean_desc"].apply(extract_merchant)

In [51]:
def fix_special_cases(row):
    text = str(row["TRANSACTION DETAILS"]).lower()
    
    if "sweep" in text:
        return "self transfer"
    elif "imps" in text and len(row["merchant"]) < 3:
        return "imps transfer"
    
    return row["merchant"]

df1["merchant"] = df1.apply(fix_special_cases, axis=1)

In [52]:
df1.head(20)

,Account No,DATE,TRANSACTION DETAILS,CHQ.NO.,VALUE DATE,WITHDRAWAL AMT,DEPOSIT AMT,BALANCE AMT,clean_desc,type,merchant
0,409000611074',2017-06-29,TRF FROM Indiaforensic SERVICES,NaN,2017-06-29,NaN,1000000.0,1000000.0,indiaforensic services,income,indiaforensic services
1,409000611074',2017-07-05,TRF FROM Indiaforensic SERVICES,NaN,2017-07-05,NaN,1000000.0,2000000.0,indiaforensic services,income,indiaforensic services
2,409000611074',2017-07-18,FDRL/INTERNAL FUND TRANSFE,NaN,2017-07-18,NaN,500000.0,2500000.0,fdrl transfe,expense,fdrl transfe
3,409000611074',2017-08-01,TRF FRM Indiaforensic SERVICES,NaN,2017-08-01,NaN,3000000.0,5500000.0,frm indiaforensic services,expense,frm indiaforensic
4,409000611074',2017-08-16,FDRL/INTERNAL FUND TRANSFE,NaN,2017-08-16,NaN,500000.0,6000000.0,fdrl transfe,expense,fdrl transfe
5,409000611074',2017-08-16,FDRL/INTERNAL FUND TRANSFE,NaN,2017-08-16,NaN,500000.0,6500000.0,fdrl transfe,expense,fdrl transfe
6,409000611074',2017-08-16,FDRL/INTERNAL FUND TRANSFE,NaN,2017-08-16,NaN,500000.0,7000000.0,fdrl transfe,expense,fdrl transfe
7,409000611074',2017-08-16,FDRL/INTERNAL FUND TRANSFE,NaN,2017-08-16,NaN,500000.0,7500000.0,fdrl transfe,expense,fdrl transfe
8,409000611074',2017-08-16,FDRL/INTERNAL FUND TRANSFE,NaN,2017-08-16,NaN,500000.0,8000000.0,fdrl transfe,expense,fdrl transfe
9,409000611074',2017-08-16,FDRL/INTERNAL FUND TRANSFE,NaN,2017-08-16,NaN,500000.0,8500000.0,fdrl transfe,expense,fdrl transfe
10,409000611074',2017-08-16,INDO GIBL Indiaforensic STL01071,NaN,2017-08-16,133900.0,NaN,8366100.0,indo gibl indiaforensic stl,expense,indo gibl
11,409000611074',2017-08-16,INDO GIBL Indiaforensic STL02071,NaN,2017-08-16,18000.0,NaN,8348100.0,indo gibl indiaforensic stl,expense,indo gibl
12,409000611074',2017-08-16,INDO GIBL Indiaforensic STL03071,NaN,2017-08-16,5000.0,NaN,8343100.0,indo gibl indiaforensic stl,expense,indo gibl
13,409000611074',2017-08-16,INDO GIBL Indiaforensic STL04071,NaN,2017-08-16,195800.0,NaN,8147300.0,indo gibl indiaforensic stl,expense,indo gibl
14,409000611074',2017-08-16,INDO GIBL Indiaforensic STL05071,NaN,2017-08-16,81600.0,NaN,8065700.0,indo gibl indiaforensic stl,expense,indo gibl
15,409000611074',2017-08-16,INDO GIBL Indiaforensic STL06071,NaN,2017-08-16,41800.0,NaN,8023900.0,indo gibl indiaforensic stl,expense,indo gibl
16,409000611074',2017-08-16,INDO GIBL Indiaforensic STL07071,NaN,2017-08-16,98500.0,NaN,7925400.0,indo gibl indiaforensic stl,expense,indo gibl
17,409000611074',2017-08-16,INDO GIBL Indiaforensic STL10071,NaN,2017-08-16,143800.0,NaN,7781600.0,indo gibl indiaforensic stl,expense,indo gibl
18,409000611074',2017-08-16,INDO GIBL Indiaforensic STL11071,NaN,2017-08-16,331650.0,NaN,7449950.0,indo gibl indiaforensic stl,expense,indo gibl
19,409000611074',2017-08-16,INDO GIBL Indiaforensic STL12071,NaN,2017-08-16,129000.0,NaN,7320950.0,indo gibl indiaforensic stl,expense,indo gibl

In [53]:
df1["category"] = "others"

In [54]:
rules = {
    "food": ["swiggy", "zomato", "restaurant", "cafe"],
    "shopping": ["amazon", "flipkart", "myntra", "ajio"],
    "travel": ["uber", "ola", "irctc", "flight"],
    "bills": ["electricity", "water", "gas", "recharge"],
    "subscription": ["netflix", "spotify", "prime"],
    "salary": ["salary", "indiaforensic"],
}

In [55]:
def categorize(row):
    merchant = str(row["merchant"]).lower()
    t_type = row["type"]
    
    # Priority 1: Type-based
    if t_type == "income":
        return "income"
    elif t_type == "transfer":
        return "transfer"
    
    # Priority 2: Merchant-based
    for category, keywords in rules.items():
        for word in keywords:
            if word in merchant:
                return category
    
    return "others"

df1["category"] = df1.apply(categorize, axis=1)

In [56]:
df1[["merchant", "type", "category"]].head(20)

                  merchant     type category
0   indiaforensic services   income   income
1   indiaforensic services   income   income
2             fdrl transfe  expense   others
3        frm indiaforensic  expense   salary
4             fdrl transfe  expense   others
5             fdrl transfe  expense   others
6             fdrl transfe  expense   others
7             fdrl transfe  expense   others
8             fdrl transfe  expense   others
9             fdrl transfe  expense   others
10               indo gibl  expense   others
11               indo gibl  expense   others
12               indo gibl  expense   others
13               indo gibl  expense   others
14               indo gibl  expense   others
15               indo gibl  expense   others
16               indo gibl  expense   others
17               indo gibl  expense   others
18               indo gibl  expense   others
19               indo gibl  expense   others

In [57]:
df1["merchant"].value_counts().head(20)

merchant
fdrl transfe              573
indo gibl                 559
unknown                   531
bbps dt                   380
indfor income             214
bbps setmnt               185
bbps settlement           116
indiaforensic services     71
sbin mr                    30
frm indiaforensic          20
bbps ox                    13
cbinh mr                    8
sbin m                      6
cbinha san                  5
sbin roh                    4
mahbh mr                    4
sbin dee                    3
sbin pra                    3
cbinha man                  3
sbin moh                    3
Name: count, dtype: int64

In [58]:
manual_map = {
    "indiaforensic services": "income",
    "self transfer": "transfer",
    "imps transfer": "transfer"
}

df1["category"] = df1["merchant"].map(manual_map).fillna(df1["category"])

In [59]:
df1.head(30)

,Account No,DATE,TRANSACTION DETAILS,CHQ.NO.,VALUE DATE,WITHDRAWAL AMT,DEPOSIT AMT,BALANCE AMT,clean_desc,type,merchant,category
0,409000611074',2017-06-29,TRF FROM Indiaforensic SERVICES,NaN,2017-06-29,NaN,1000000.0,1000000.0,indiaforensic services,income,indiaforensic services,income
1,409000611074',2017-07-05,TRF FROM Indiaforensic SERVICES,NaN,2017-07-05,NaN,1000000.0,2000000.0,indiaforensic services,income,indiaforensic services,income
2,409000611074',2017-07-18,FDRL/INTERNAL FUND TRANSFE,NaN,2017-07-18,NaN,500000.0,2500000.0,fdrl transfe,expense,fdrl transfe,others
3,409000611074',2017-08-01,TRF FRM Indiaforensic SERVICES,NaN,2017-08-01,NaN,3000000.0,5500000.0,frm indiaforensic services,expense,frm indiaforensic,salary
4,409000611074',2017-08-16,FDRL/INTERNAL FUND TRANSFE,NaN,2017-08-16,NaN,500000.0,6000000.0,fdrl transfe,expense,fdrl transfe,others
5,409000611074',2017-08-16,FDRL/INTERNAL FUND TRANSFE,NaN,2017-08-16,NaN,500000.0,6500000.0,fdrl transfe,expense,fdrl transfe,others
6,409000611074',2017-08-16,FDRL/INTERNAL FUND TRANSFE,NaN,2017-08-16,NaN,500000.0,7000000.0,fdrl transfe,expense,fdrl transfe,others
7,409000611074',2017-08-16,FDRL/INTERNAL FUND TRANSFE,NaN,2017-08-16,NaN,500000.0,7500000.0,fdrl transfe,expense,fdrl transfe,others
8,409000611074',2017-08-16,FDRL/INTERNAL FUND TRANSFE,NaN,2017-08-16,NaN,500000.0,8000000.0,fdrl transfe,expense,fdrl transfe,others
9,409000611074',2017-08-16,FDRL/INTERNAL FUND TRANSFE,NaN,2017-08-16,NaN,500000.0,8500000.0,fdrl transfe,expense,fdrl transfe,others
10,409000611074',2017-08-16,INDO GIBL Indiaforensic STL01071,NaN,2017-08-16,133900.0,NaN,8366100.0,indo gibl indiaforensic stl,expense,indo gibl,others
11,409000611074',2017-08-16,INDO GIBL Indiaforensic STL02071,NaN,2017-08-16,18000.0,NaN,8348100.0,indo gibl indiaforensic stl,expense,indo gibl,others
12,409000611074',2017-08-16,INDO GIBL Indiaforensic STL03071,NaN,2017-08-16,5000.0,NaN,8343100.0,indo gibl indiaforensic stl,expense,indo gibl,others
13,409000611074',2017-08-16,INDO GIBL Indiaforensic STL04071,NaN,2017-08-16,195800.0,NaN,8147300.0,indo gibl indiaforensic stl,expense,indo gibl,others
14,409000611074',2017-08-16,INDO GIBL Indiaforensic STL05071,NaN,2017-08-16,81600.0,NaN,8065700.0,indo gibl indiaforensic stl,expense,indo gibl,others
15,409000611074',2017-08-16,INDO GIBL Indiaforensic STL06071,NaN,2017-08-16,41800.0,NaN,8023900.0,indo gibl indiaforensic stl,expense,indo gibl,others
16,409000611074',2017-08-16,INDO GIBL Indiaforensic STL07071,NaN,2017-08-16,98500.0,NaN,7925400.0,indo gibl indiaforensic stl,expense,indo gibl,others
17,409000611074',2017-08-16,INDO GIBL Indiaforensic STL10071,NaN,2017-08-16,143800.0,NaN,7781600.0,indo gibl indiaforensic stl,expense,indo gibl,others
18,409000611074',2017-08-16,INDO GIBL Indiaforensic STL11071,NaN,2017-08-16,331650.0,NaN,7449950.0,indo gibl indiaforensic stl,expense,indo gibl,others
19,409000611074',2017-08-16,INDO GIBL Indiaforensic STL12071,NaN,2017-08-16,129000.0,NaN,7320950.0,indo gibl indiaforensic stl,expense,indo gibl,others
20,409000611074',2017-08-16,INDO GIBL Indiaforensic STL13071,NaN,2017-08-16,230013.0,NaN,7090937.0,indo gibl indiaforensic stl,expense,indo gibl,others
21,409000611074',2017-08-16,INDO GIBL Indiaforensic STL14071,NaN,2017-08-16,367900.0,NaN,6723037.0,indo gibl indiaforensic stl,expense,indo gibl,others
22,409000611074',2017-08-16,INDO GIBL Indiaforensic STL15071,NaN,2017-08-16,108000.0,NaN,6615037.0,indo gibl indiaforensic stl,expense,indo gibl,others
23,409000611074',2017-08-16,INDO GIBL Indiaforensic STL16071,NaN,2017-08-16,64800.0,NaN,6550237.0,indo gibl indiaforensic stl,expense,indo gibl,others
24,409000611074',2017-08-16,INDO GIBL Indiaforensic STL17071,NaN,2017-08-16,141000.0,NaN,6409237.0,indo gibl indiaforensic stl,expense,indo gibl,others
25,409000611074',2017-08-16,INDO GIBL Indiaforensic STL18071,NaN,2017-08-16,61750.0,NaN,6347487.0,indo gibl indiaforensic stl,expense,indo gibl,others
26,409000611074',2017-08-16,INDO GIBL Indiaforensic STL19071,NaN,2017-08-16,67920.0,NaN,6279567.0,indo gibl indiaforensic stl,expense,indo gibl,others
27,409000611074',2017-08-16,INDO GIBL Indiaforensic STL20071,NaN,2017-08-16,78100.0,NaN,6201467.0,indo gibl indiaforensic stl,expense,indo gibl,others
28,409000611074',2017-08-16,INDO GIBL Indiaforensic STL21071,NaN,2017-08-16,35650.0,NaN,6165817.0,indo gibl indiaforensic stl,expense,indo gibl,others
29,409000611074',2017-08-16,INDO GIBL Indiaforensic STL22071,NaN,2017-08-16,206000.0,NaN,5959817.0,indo gibl indiaforensic stl,expense,indo gibl,others

In [60]:
df1.shape

(2925, 12)

In [61]:
df1["category"].value_counts()

category
others      2831
income        71
salary        21
transfer       2
Name: count, dtype: int64

In [62]:
top_merchants = df1["merchant"].value_counts().head(100)
print(top_merchants)

merchant
fdrl transfe     573
indo gibl        559
unknown          531
bbps dt          380
indfor income    214
                ...
cbinha sun         1
sbin md            1
barbh man          1
bkidn amr          1
sbin kun           1
Name: count, Length: 100, dtype: int64

In [63]:
df1[df1["category"] == "others"]["merchant"].value_counts().head(20)

merchant
fdrl transfe       573
indo gibl          559
unknown            531
bbps dt            380
indfor income      214
bbps setmnt        185
bbps settlement    116
sbin mr             30
bbps ox             13
cbinh mr             8
sbin m               6
cbinha san           5
sbin roh             4
mahbh mr             4
sbin dee             3
sbin pra             3
cbinha man           3
sbin moh             3
cbinha son           3
sbin san             3
Name: count, dtype: int64

In [64]:
df1 = df1.sort_values(by="DATE")

In [65]:
grouped = df1.groupby("merchant")

In [66]:
recurring_list = []

for merchant, group in grouped:
    
    if len(group) < 3:
        continue  
    
    group = group.sort_values("DATE")
    
    group["diff_days"] = group["DATE"].diff().dt.days
    
    avg_gap = group["diff_days"].mean()
    
    if 25 <= avg_gap <= 35:
        recurring_list.append((merchant, avg_gap))

In [67]:
recurring_df = pd.DataFrame(recurring_list, columns=["merchant", "avg_days"])
print(recurring_df)

   merchant  avg_days
0  cbinh mr      29.0
1    sbin m      26.6

In [68]:
df1["recurring"] = df1["merchant"].isin(recurring_df["merchant"])

In [69]:
df1["amount"] = df1["DEPOSIT AMT"].fillna(0) - df1["WITHDRAWAL AMT"].fillna(0)

In [70]:
for merchant, group in grouped:
    
    if len(group) < 3:
        continue
    
    group = group.sort_values("DATE")
    
    group["diff_days"] = group["DATE"].diff().dt.days
    avg_gap = group["diff_days"].mean()
    
    amount_std = group["amount"].std()
    
    if 25 <= avg_gap <= 35 and amount_std < 100: 
        recurring_list.append((merchant, avg_gap))

In [71]:
def recurring_type(days):
    if 25 <= days <= 35:
        return "monthly"
    elif 6 <= days <= 8:
        return "weekly"
    else:
        return "other"

recurring_df["type"] = recurring_df["avg_days"].apply(recurring_type)

In [72]:
total_income = df1[df1["amount"] > 0]["amount"].sum()
print("Total Income:", total_income)

Total Income: 260936637.76999998

In [73]:
total_spent = df1[df1["amount"] < 0]["amount"].sum()
total_spent = abs(total_spent)

print("Total Spent:", total_spent)

Total Spent: 245477437.42

In [74]:
current_balance = total_income - total_spent

In [75]:
num_days = (df1["DATE"].max() - df1["DATE"].min()).days

daily_spent = total_spent / num_days

print("Daily Spending:", daily_spent)

Daily Spending: 221950.66674502712

In [76]:
category_spent = df1[df1["amount"] < 0].groupby("category")["amount"].sum()

# convert to positive
category_spent = abs(category_spent)

category_daily = category_spent / num_days

print(category_daily)

category
income       31918.444846
others      189489.726420
salary         452.079566
transfer        90.415913
Name: amount, dtype: float64

In [77]:
def calculate_safe_spend(df1):
    current_balance = total_income - total_spent
    
    recurring = df1[(df1["recurring"] == True) & (df1["amount"] < 0)]["amount"].sum()
    recurring = abs(recurring)
    
    remaining = current_balance - recurring
    
    safe_daily = remaining / 30
    
    return safe_daily

In [78]:
expenses = df1[df1["amount"] < 0].copy()

In [79]:
grouped = expenses.groupby("category")

In [80]:
anomalies = []

for category, group in grouped:
    
    if len(group) < 5:
        continue  # skip small data
    
    mean = group["amount"].mean()
    std = group["amount"].std()
    
    for i, row in group.iterrows():
        z_score = (row["amount"] - mean) / std if std != 0 else 0
        
        if abs(z_score) > 2:  # threshold
            anomalies.append(row)

In [81]:
anomaly_df = pd.DataFrame(anomalies)

print(anomaly_df[["DATE", "merchant", "amount", "category"]])

           DATE                merchant      amount category
1947 2018-11-06  indiaforensic services -2000000.00   income
1954 2018-11-12  indiaforensic services -2500000.00   income
2004 2018-12-17  indiaforensic services -2000000.00   income
1274 2017-06-12         bbps settlement  -856588.64   others
1296 2017-06-27         bbps settlement  -540324.73   others
...         ...                     ...         ...      ...
1037 2019-01-14               indo gibl  -727659.00   others
1054 2019-01-18               indo gibl  -628628.00   others
1066 2019-01-22               indo gibl  -602930.00   others
1069 2019-01-23               indo gibl  -589137.00   others
1092 2019-02-08            fdrl transfe  -600000.00   others

[88 rows x 4 columns]

In [82]:
def financial_summary(df1):

    # Income
    total_income = df1[df1["amount"] > 0]["amount"].sum()
    
    # Spent
    total_spent = abs(df1[df1["amount"] < 0]["amount"].sum())
    
    # Balance
    
    current_balance = total_income - total_spent
    
    # Days
    num_days = max(1, (df1["DATE"].max() - df1["DATE"].min()).days)
    
    # Daily spend
    daily_spent = total_spent / num_days
    
    
    return total_income, total_spent,  current_balance, daily_spent, num_days

In [83]:
def category_summary(df1):

    num_days = max(1, (df1["DATE"].max() - df1["DATE"].min()).days)
    
    category_spent = df1[df1["amount"] < 0].groupby("category")["amount"].sum()
    
    category_spent = abs(category_spent)
    
    category_daily = category_spent / num_days
    
    return category_daily

In [84]:
safe_spend = calculate_safe_spend(df1)

In [85]:
print("⚠️ Unusual Transactions:")
print(anomaly_df[["DATE", "merchant", "amount", "category"]])

⚠️ Unusual Transactions:
           DATE                merchant      amount category
1947 2018-11-06  indiaforensic services -2000000.00   income
1954 2018-11-12  indiaforensic services -2500000.00   income
2004 2018-12-17  indiaforensic services -2000000.00   income
1274 2017-06-12         bbps settlement  -856588.64   others
1296 2017-06-27         bbps settlement  -540324.73   others
...         ...                     ...         ...      ...
1037 2019-01-14               indo gibl  -727659.00   others
1054 2019-01-18               indo gibl  -628628.00   others
1066 2019-01-22               indo gibl  -602930.00   others
1069 2019-01-23               indo gibl  -589137.00   others
1092 2019-02-08            fdrl transfe  -600000.00   others

[88 rows x 4 columns]

In [86]:
financial_summary(df1)

(np.float64(260936637.76999998),
 np.float64(245477437.42),
 np.float64(15459200.349999994),
 np.float64(221950.66674502712),
 1106)

In [87]:
category_summary(df1)

category
income       31918.444846
others      189489.726420
salary         452.079566
transfer        90.415913
Name: amount, dtype: float64